import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:pokedex/features/nav/cubit/bottom_nav_cubit.dart';
import 'package:pokedex/features/pokemon/bloc/pokemon_bloc.dart';
import 'package:pokedex/features/pokemon/bloc/pokemon_details_cubit.dart';
import 'package:pokedex/features/pokemon/data/repositories/pokemon_repository.dart';
import 'package:pokedex/features/nav/presentation/pages/home_view.dart';
import 'package:pokedex/features/favorites/bloc/favorites_cubit.dart';
import 'package:pokedex/features/pokemon/bloc/pokemon_event.dart';
import 'package:pokedex/features/nav/cubit/nav_cubit.dart';

// Auto-generated by FlutterFire CLI (mocking for now if missing)
import 'package:firebase_core/firebase_core.dart';
import 'package:pokedex/features/auth/data/auth_repository.dart';
import 'package:pokedex/features/auth/bloc/auth_cubit.dart';
import 'package:pokedex/features/auth/presentation/pages/login_view.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  try {
    await Firebase.initializeApp();
  } catch (e) {
    print('Firebase initialization failed (Expected if config missing): $e');
  }

  runApp(PokedexApp());
}

class PokedexApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final pokemonDetailsCubit = PokemonDetailsCubit();

    return MultiBlocProvider(
      providers: [
        BlocProvider(
            create: (context) =>
                PokemonBloc()..add(PokemonPageRequest(page: 0))),
        BlocProvider(
            create: (context) =>
                NavCubit(pokemonDetailsCubit: pokemonDetailsCubit)),
        BlocProvider(create: (context) => pokemonDetailsCubit),
        BlocProvider(create: (context) => BottomNavCubit()),
        BlocProvider(create: (context) => FavoritesCubit()),
        BlocProvider(create: (context) => AuthCubit(AuthRepository())),
      ],
      child: MaterialApp(
        title: 'Pokedex',
        theme: ThemeData(
          primarySwatch: Colors.red,
          visualDensity: VisualDensity.adaptivePlatformDensity,
        ),
        home: BlocBuilder<AuthCubit, AuthState>(
          builder: (context, state) {
            if (state is AuthAuthenticated) {
              return HomeView();
            } else if (state is AuthUnauthenticated) {
              return LoginView();
            } else {
              // Initial state
              return LoginView();
            }
          },
        ),
      ),
    );
  }
}
